default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: zodiac_aerospace_app_development

test:
  <<: *default
  database: zodiac_aerospace_app_test

production:
  <<: *default
  database: zodiac_aerospace_app_production
  username: zodiac_aerospace_app
  password: <%= ENV['zodiac_aerospace_app_DATABASE_PASSWORD'] %>
